#!/bin/sh
exec java -Dfile.encoding=UTF-8 -classpath $HOME/jonas/scarlett/jacktools/target/classes:$HOME/.m2/repository/org/jaudiolibs/jnajack/1.4.0/jnajack-1.4.0.jar:$HOME/.m2/repository/net/java/dev/jna/jna/5.5.0/jna-5.5.0.jar space.xkr47.jacktools.Patchbay
